In [7]:
import tensorflow as tf

x = tf.constant([[5., 5., 5.],
                 [2., 2., 2.]])

with tf.Session() as sess:
    print(tf.reduce_mean(x).eval())
    print(tf.reduce_mean(x, reduction_indices=0).eval())
    print(tf.reduce_mean(x, axis=0).eval())
    print(tf.reduce_mean(x, axis=1).eval())
    print(tf.reduce_mean(x, axis=1, keepdims=True).eval())

3.5
[3.5 3.5 3.5]
[3.5 3.5 3.5]
[5. 2.]
[[5.]
 [2.]]
