In [20]:
import numpy as np

## Epsilon decay example run

In [21]:
total_episodes = 100
for episode_num in range(total_episodes):
    epsilon = 1.0 / ((episode_num/10) + 1)
    print(epsilon)

1.0
0.9090909090909091
0.8333333333333334
0.7692307692307692
0.7142857142857143
0.6666666666666666
0.625
0.5882352941176471
0.5555555555555556
0.5263157894736842
0.5
0.47619047619047616
0.45454545454545453
0.4347826086956522
0.4166666666666667
0.4
0.3846153846153846
0.37037037037037035
0.35714285714285715
0.3448275862068966
0.3333333333333333
0.3225806451612903
0.3125
0.30303030303030304
0.29411764705882354
0.2857142857142857
0.2777777777777778
0.27027027027027023
0.2631578947368421
0.25641025641025644
0.25
0.24390243902439027
0.23809523809523808
0.23255813953488372
0.22727272727272727
0.2222222222222222
0.2173913043478261
0.2127659574468085
0.20833333333333334
0.2040816326530612
0.2
0.19607843137254904
0.1923076923076923
0.18867924528301888
0.18518518518518517
0.18181818181818182
0.17857142857142858
0.17543859649122806
0.1724137931034483
0.1694915254237288
0.16666666666666666
0.1639344262295082
0.16129032258064516
0.15873015873015872
0.15625
0.15384615384615385
0.15151515151515152
0.1

## Numpy vstack and array

In [23]:
li = [i for i in range(16)]
print("Original list", li)
print("np.array", np.array(li))
print("np.vstack", np.vstack(li))

Original list [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
np.array (16,)
np.vstack (16, 1)


## Selective update per row in numpy

In [28]:
batch_size = 16
output_size = 2
output = np.random.rand(batch_size, output_size)
print(output)

[[0.41454458 0.69148317]
 [0.13198683 0.1676082 ]
 [0.54158775 0.41234773]
 [0.6382836  0.67920687]
 [0.48358896 0.55321803]
 [0.64298348 0.83147633]
 [0.64820842 0.35101376]
 [0.66553226 0.29942524]
 [0.8016464  0.69382183]
 [0.88398066 0.87685901]
 [0.63673801 0.3192367 ]
 [0.97868439 0.56916358]
 [0.9431858  0.34039779]
 [0.47905045 0.27747439]
 [0.1494829  0.05539976]
 [0.14636952 0.82548782]]


In [29]:
output[0, 0] = -1
print(output)

[[-1.          0.69148317]
 [ 0.13198683  0.1676082 ]
 [ 0.54158775  0.41234773]
 [ 0.6382836   0.67920687]
 [ 0.48358896  0.55321803]
 [ 0.64298348  0.83147633]
 [ 0.64820842  0.35101376]
 [ 0.66553226  0.29942524]
 [ 0.8016464   0.69382183]
 [ 0.88398066  0.87685901]
 [ 0.63673801  0.3192367 ]
 [ 0.97868439  0.56916358]
 [ 0.9431858   0.34039779]
 [ 0.47905045  0.27747439]
 [ 0.1494829   0.05539976]
 [ 0.14636952  0.82548782]]


In [30]:
output[[0, 1], 0] = -1
print(output)

[[-1.          0.69148317]
 [-1.          0.1676082 ]
 [ 0.54158775  0.41234773]
 [ 0.6382836   0.67920687]
 [ 0.48358896  0.55321803]
 [ 0.64298348  0.83147633]
 [ 0.64820842  0.35101376]
 [ 0.66553226  0.29942524]
 [ 0.8016464   0.69382183]
 [ 0.88398066  0.87685901]
 [ 0.63673801  0.3192367 ]
 [ 0.97868439  0.56916358]
 [ 0.9431858   0.34039779]
 [ 0.47905045  0.27747439]
 [ 0.1494829   0.05539976]
 [ 0.14636952  0.82548782]]


In [31]:
to_update_rows = np.arange(16)
print(to_update_rows)

to_update_cols = [i % 2 for i in range(16)]
print(to_update_cols)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [32]:
output[to_update_rows, to_update_cols] = 0.0
print(output)

[[ 0.          0.69148317]
 [-1.          0.        ]
 [ 0.          0.41234773]
 [ 0.6382836   0.        ]
 [ 0.          0.55321803]
 [ 0.64298348  0.        ]
 [ 0.          0.35101376]
 [ 0.66553226  0.        ]
 [ 0.          0.69382183]
 [ 0.88398066  0.        ]
 [ 0.          0.3192367 ]
 [ 0.97868439  0.        ]
 [ 0.          0.34039779]
 [ 0.47905045  0.        ]
 [ 0.          0.05539976]
 [ 0.14636952  0.        ]]
